# Generated by Django 4.2.5 on 2023-09-27 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'store_category',
                'verbose_name_plural': 'store_categorys',
                'db_table': 'restuarant_store_category',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StoreOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'store owner',
                'verbose_name_plural': 'store owners',
                'db_table': 'restuarant_store_owner',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('tagline', models.CharField(max_length=50)),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('category', models.ManyToManyField(to='restaurant.storecategory')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.storeowner')),
            ],
            options={
                'verbose_name': 'restaurant',
                'verbose_name_plural': 'restaurants',
                'db_table': 'restuarant_restaurant',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
            options={
                'verbose_name': 'food_category',
                'verbose_name_plural': 'food_categorys',
                'db_table': 'restuarant_food_category',
                'ordering': ['-id'],
            },
        ),
    ]
