# Generated by Django 4.2.5 on 2023-10-12 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_food'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['-id'], 'verbose_name': 'food', 'verbose_name_plural': 'foods'},
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='food',
            name='category',
        ),
        migrations.AlterModelTable(
            name='food',
            table='restuarant_food',
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurant.foodcategory'),
            preserve_default=False,
        ),
    ]
